Feat Menu and login and Registration page
dream-wish-team/wish-board pull request #4
Opened 2021-01-05 17:41 UTC by SkaymanT

1. Implement MenuBar page
2. Implement Login (user: test; password: 123456) need start server server(https://github.com/dream-wish-team/graphql-server-wishboard)
3. Implement routing withAutorization
4. Now doing Registration Page

2021-01-05 17:54 UTC, valerydluski commented on src/components/MenuBar/MenuBar.tsx
> +    <div>
Тут нужен этот div?

2021-01-05 17:54 UTC, valerydluski commented on src/customHooks/auth.hook.ts
> +    if (data && data.token && data.id) {
(data?.token && data?.id) почему не используешь современные фишки?)

2021-01-05 17:54 UTC, valerydluski commented on src/pages/App.tsx
> +  if (routeName && routeName.indexOf('@') !== 1) {
routeName?.indexOf('@') !== 1

2021-01-05 18:05 UTC, SkaymanT commented on src/customHooks/auth.hook.ts
> +    if (data && data.token && data.id) {
Потому люблю гов...код) Пофиксил

2021-01-05 18:05 UTC, SkaymanT commented on src/pages/App.tsx
> +  if (routeName && routeName.indexOf('@') !== 1) {
Пофиксил

2021-01-05 18:08 UTC, SkaymanT commented on src/customHooks/auth.hook.ts
> +    if (data && data.token && data.id) {
Cпасибо

2021-01-05 18:15 UTC, micolka commented on src/pages/App.tsx
> +});
у тебя бэк локальный похоже. а нам что делать?

2021-01-05 18:22 UTC, micolka reviewed
1. Что за компонент menuBar? Не вижу такой карточки в трелло. 
2.  По бэку. Тебе где-то нужно начинать описывать его работу, как в любой нормальной доке по апи (пригодится в статье). Чтобы не только ты мог им пользоваться и тестить. Плюс нужно задуматься над размещением сервака в сети

2021-01-05 18:23 UTC, SkaymanT commented on src/pages/App.tsx
> +});
Он есть в тиме репозитории, форкнуть и запустить... Я буду в него вносить поля, смысла пока нету заливать на хероку или что-то подобное.

2021-01-05 18:24 UTC, Alexey-Koren commented on src/pages/App.tsx
> +});
Согласен, потом перенесётё когда прод тестить будете

2021-01-05 18:40 UTC, micolka commented on src/pages/App.tsx
> +});
тогда в чате сделай анонс с инструкцией по использованию.

2021-01-05 19:25 UTC, Alexey-Koren requested changes

2021-01-05 19:25 UTC, alexey-koran commented on src/pages/FriendsPage/FriendsPage.tsx
> +const FriendsPage: React.FC = () => <div className={styles['home-page']}>FriendsPage</div>;
```suggestion
import React from 'react';
import type { FunctionComponent, HTMLAttributes } from 'react';

import styles from '@/pages/FriendsPage/FriendsPage.scss';

const FriendsPage: FunctionComponent<HTMLAttributes<HTMLDivElement>> = () => (
  <div className={styles['home-page']}>FriendsPage</div>
);

export default FriendsPage;
```

2021-01-05 19:25 UTC, alexey-koran commented on src/pages/FriendsPage/FriendsPage.tsx
> +const FriendsPage: React.FC = () => <div className={styles['home-page']}>FriendsPage</div>;
Во всех компонентах исправь как тут сделал. Только смотри какой главный тег куда ты пропы прокидываешь, такой интерфейс и подтягивай

2021-01-05 19:25 UTC, alexey-koran commented on src/components/MenuBar/MenuBar.tsx
> +import { createStyles, makeStyles, Theme } from '@material-ui/core/styles';
```suggestion
import { createStyles, makeStyles } from '@material-ui/core/styles';
import type { Theme } from '@material-ui/core/styles';
```

2021-01-05 19:25 UTC, alexey-koran commented on src/components/MenuBar/MenuBar.tsx
> +  children: React.ReactNode;
```suggestion
  children: ReactNode;
```

2021-01-05 19:25 UTC, alexey-koran commented on src/components/MenuBar/MenuBar.tsx
> +import type { FunctionComponent, HTMLAttributes } from 'react';
```suggestion
import type { FunctionComponent, HTMLAttributes, ReactNode } from 'react';
```

2021-01-05 19:25 UTC, Alexey-Koren commented on src/components/MenuBar/MenuBar.tsx
> +    <div>
По идее да, он типа я так понимаю обёртка просто, потом это в апе вызывается

2021-01-05 19:25 UTC, Alexey-Koren commented on src/components/MenuBar/MenuBar.tsx
> +  const [anchorEl, setAnchorEl] = React.useState<null | HTMLElement>(null);
```suggestion
  const [anchorEl, setAnchorEl] = useState<null | HTMLElement>(null);
```

2021-01-05 19:25 UTC, Alexey-Koren commented on src/components/MenuBar/MenuBar.tsx
> +import React, { Fragment, useContext } from 'react';
```suggestion
import React, { Fragment, useState, useContext } from 'react';
```

2021-01-05 19:25 UTC, Alexey-Koren commented on src/components/MenuBar/MenuBar.tsx
> +  const handleMenu = (event: React.MouseEvent<HTMLElement>) => {
Во всём проекте убери глобальное обращение к реакту, на импорты и раскидай интерфейсы в import type. Так будет проще читать код и все зависимости сразу видны сверху компонента
```suggestion
  const handleMenu = (event: MouseEvent<HTMLElement>) => {
```

2021-01-05 19:25 UTC, Alexey-Koren commented on src/components/MenuBar/MenuBar.tsx
> +interface PropsMenu extends HTMLAttributes<HTMLElement> {
```suggestion
interface PropsMenu extends HTMLAttributes<HTMLDivElement> {
```

2021-01-05 19:25 UTC, Alexey-Koren commented on src/customHooks/form.hooks.ts
> +import { IUserForm, IValues } from '@/types/hooks';
```suggestion
import type { IUserForm, IValues } from '@/types/hooks';
```

2021-01-05 19:25 UTC, Alexey-Koren commented on src/pages/AuthPage/AuthPage.tsx
> +import { RouteComponentProps } from 'react-router-dom';
Проверь чтобы везде где ты импортишь интерфейс был import type

```suggestion
import type { RouteComponentProps } from 'react-router-dom';
```

2021-01-05 19:25 UTC, Alexey-Koren commented on src/pages/AuthPage/AuthPage.tsx
> +import React, { FunctionComponent, useContext, useState } from 'react';
```suggestion
import React, { FunctionComponent, HTMLAttributes, useContext, useState } from 'react';
```

2021-01-05 19:25 UTC, Alexey-Koren commented on src/pages/AuthPage/AuthPage.tsx
> +const AuthPage: FunctionComponent<RouteComponentProps> = props => {
```suggestion
type AuthPageProps = RouteComponentProps & HTMLAttributes<HTMLFormElement>;

const AuthPage: FunctionComponent<AuthPageProps> = ({...props }) => {
```

2021-01-06 13:19 UTC, SkaymanT commented on src/pages/FriendsPage/FriendsPage.tsx
> +const FriendsPage: React.FC = () => <div className={styles['home-page']}>FriendsPage</div>;
ok, подправил

2021-01-06 13:32 UTC, SkaymanT commented on src/components/MenuBar/MenuBar.tsx
> +import { createStyles, makeStyles, Theme } from '@material-ui/core/styles';
Подправил

2021-01-06 13:33 UTC, SkaymanT commented on src/components/MenuBar/MenuBar.tsx
> +import type { FunctionComponent, HTMLAttributes } from 'react';
Подправил

2021-01-06 13:34 UTC, SkaymanT commented on src/components/MenuBar/MenuBar.tsx
> +  const [anchorEl, setAnchorEl] = React.useState<null | HTMLElement>(null);
Хотел вешать класс но потом передумал

2021-01-06 13:35 UTC, SkaymanT commented on src/components/MenuBar/MenuBar.tsx
> +interface PropsMenu extends HTMLAttributes<HTMLElement> {
fix

2021-01-06 13:36 UTC, SkaymanT commented on src/components/MenuBar/MenuBar.tsx
> +  const handleMenu = (event: React.MouseEvent<HTMLElement>) => {
fix

2021-01-06 13:36 UTC, SkaymanT commented on src/components/MenuBar/MenuBar.tsx
> +import React, { Fragment, useContext } from 'react';
fix

2021-01-06 13:38 UTC, SkaymanT commented on src/customHooks/form.hooks.ts
> +import { IUserForm, IValues } from '@/types/hooks';
fix

2021-01-06 13:39 UTC, SkaymanT commented on src/pages/AuthPage/AuthPage.tsx
> +import { RouteComponentProps } from 'react-router-dom';
fix

2021-01-06 13:40 UTC, SkaymanT commented on src/pages/AuthPage/AuthPage.tsx
> +import React, { FunctionComponent, useContext, useState } from 'react';
fix

2021-01-06 13:40 UTC, SkaymanT commented on src/pages/AuthPage/AuthPage.tsx
> +const AuthPage: FunctionComponent<RouteComponentProps> = props => {
fix

2021-01-06 13:49 UTC, SkaymanT commented on src/components/MenuBar/MenuBar.tsx
> +  const handleMenu = (event: React.MouseEvent<HTMLElement>) => {
error: Type 'MouseEvent' is not generic.

2021-01-06 16:24 UTC, merged